/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PrivateRentalMatchingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addPauser"
      | "confirmMatch"
      | "createListing"
      | "createMatch"
      | "createRequest"
      | "deactivateListing"
      | "deactivateRequest"
      | "decryptionRequestCounter"
      | "decryptionRequests"
      | "emergencyPause"
      | "getActiveListingsCount"
      | "getActiveRequestsCount"
      | "getListingDetails"
      | "getMatchDetails"
      | "getPauserAtIndex"
      | "getPauserCount"
      | "getPlatformStats"
      | "getRequestDetails"
      | "getUserListings"
      | "getUserRequests"
      | "isContractPaused"
      | "isListingValid"
      | "isPaused"
      | "isPauser"
      | "isPauserAddress"
      | "isPublicDecryptAllowed"
      | "isRequestValid"
      | "kmsGeneration"
      | "listingIdCounter"
      | "listings"
      | "matchCounter"
      | "matches"
      | "owner"
      | "pause"
      | "pauserAddresses"
      | "protocolId"
      | "removePauser"
      | "requestDecryption"
      | "requestIdCounter"
      | "requests"
      | "submitDecryptionResponse"
      | "unpause"
      | "updateKmsGeneration"
      | "userListings"
      | "userRequests"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ContractPaused"
      | "ContractUnpaused"
      | "DecryptionRequested"
      | "DecryptionResponse"
      | "KmsGenerationUpdated"
      | "ListingCreated"
      | "ListingDeactivated"
      | "MatchConfirmed"
      | "MatchCreated"
      | "PauserAdded"
      | "PauserRemoved"
      | "RequestCreated"
      | "RequestDeactivated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addPauser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmMatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createListing",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createMatch",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createRequest",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateListing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "decryptionRequestCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "decryptionRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyPause",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveListingsCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveRequestsCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getListingDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMatchDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPauserAtIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPauserCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPlatformStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRequestDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserListings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserRequests",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isContractPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isListingValid",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "isPaused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isPauser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPauserAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPublicDecryptAllowed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isRequestValid",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "kmsGeneration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "listingIdCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "listings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "matchCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "matches",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pauserAddresses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removePauser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestDecryption",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestIdCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitDecryptionResponse",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateKmsGeneration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userListings",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userRequests",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addPauser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confirmMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decryptionRequestCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decryptionRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyPause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveListingsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveRequestsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getListingDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMatchDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPauserAtIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPauserCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlatformStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRequestDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserListings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isContractPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isListingValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isPaused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isPauser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isPauserAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPublicDecryptAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRequestValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "kmsGeneration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listingIdCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listings", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "matchCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "matches", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauserAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removePauser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestIdCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "requests", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitDecryptionResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateKmsGeneration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userListings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userRequests",
    data: BytesLike
  ): Result;
}

export namespace ContractPausedEvent {
  export type InputTuple = [by: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [by: string, timestamp: bigint];
  export interface OutputObject {
    by: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractUnpausedEvent {
  export type InputTuple = [by: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [by: string, timestamp: bigint];
  export interface OutputObject {
    by: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DecryptionRequestedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    requester: AddressLike,
    kmsGeneration: BigNumberish,
    encryptedValue: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    requestId: bigint,
    requester: string,
    kmsGeneration: bigint,
    encryptedValue: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    requestId: bigint;
    requester: string;
    kmsGeneration: bigint;
    encryptedValue: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DecryptionResponseEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    kmsNode: AddressLike,
    encryptedShare: BytesLike,
    signature: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    requestId: bigint,
    kmsNode: string,
    encryptedShare: string,
    signature: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    requestId: bigint;
    kmsNode: string;
    encryptedShare: string;
    signature: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KmsGenerationUpdatedEvent {
  export type InputTuple = [
    oldGeneration: BigNumberish,
    newGeneration: BigNumberish
  ];
  export type OutputTuple = [oldGeneration: bigint, newGeneration: bigint];
  export interface OutputObject {
    oldGeneration: bigint;
    newGeneration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ListingCreatedEvent {
  export type InputTuple = [listingId: BigNumberish, landlord: AddressLike];
  export type OutputTuple = [listingId: bigint, landlord: string];
  export interface OutputObject {
    listingId: bigint;
    landlord: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ListingDeactivatedEvent {
  export type InputTuple = [listingId: BigNumberish];
  export type OutputTuple = [listingId: bigint];
  export interface OutputObject {
    listingId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchConfirmedEvent {
  export type InputTuple = [matchId: BigNumberish, confirmer: AddressLike];
  export type OutputTuple = [matchId: bigint, confirmer: string];
  export interface OutputObject {
    matchId: bigint;
    confirmer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchCreatedEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    listingId: BigNumberish,
    requestId: BigNumberish
  ];
  export type OutputTuple = [
    matchId: bigint,
    listingId: bigint,
    requestId: bigint
  ];
  export interface OutputObject {
    matchId: bigint;
    listingId: bigint;
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PauserAddedEvent {
  export type InputTuple = [pauser: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [pauser: string, timestamp: bigint];
  export interface OutputObject {
    pauser: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PauserRemovedEvent {
  export type InputTuple = [pauser: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [pauser: string, timestamp: bigint];
  export interface OutputObject {
    pauser: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestCreatedEvent {
  export type InputTuple = [requestId: BigNumberish, tenant: AddressLike];
  export type OutputTuple = [requestId: bigint, tenant: string];
  export interface OutputObject {
    requestId: bigint;
    tenant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestDeactivatedEvent {
  export type InputTuple = [requestId: BigNumberish];
  export type OutputTuple = [requestId: bigint];
  export interface OutputObject {
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PrivateRentalMatching extends BaseContract {
  connect(runner?: ContractRunner | null): PrivateRentalMatching;
  waitForDeployment(): Promise<this>;

  interface: PrivateRentalMatchingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addPauser: TypedContractMethod<[_pauser: AddressLike], [void], "nonpayable">;

  confirmMatch: TypedContractMethod<
    [_matchId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createListing: TypedContractMethod<
    [
      _price: BigNumberish,
      _bedrooms: BigNumberish,
      _postalCode: BigNumberish,
      _propertyType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  createMatch: TypedContractMethod<
    [_listingId: BigNumberish, _requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createRequest: TypedContractMethod<
    [
      _maxBudget: BigNumberish,
      _minBedrooms: BigNumberish,
      _preferredPostalCode: BigNumberish,
      _preferredPropertyType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  deactivateListing: TypedContractMethod<
    [_listingId: BigNumberish],
    [void],
    "nonpayable"
  >;

  deactivateRequest: TypedContractMethod<
    [_requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  decryptionRequestCounter: TypedContractMethod<[], [bigint], "view">;

  decryptionRequests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, boolean, bigint] & {
        requestId: bigint;
        requester: string;
        encryptedValue: string;
        timestamp: bigint;
        fulfilled: boolean;
        kmsGeneration: bigint;
      }
    ],
    "view"
  >;

  emergencyPause: TypedContractMethod<[], [void], "nonpayable">;

  getActiveListingsCount: TypedContractMethod<[], [bigint], "view">;

  getActiveRequestsCount: TypedContractMethod<[], [bigint], "view">;

  getListingDetails: TypedContractMethod<
    [_listingId: BigNumberish],
    [
      [boolean, string, bigint, boolean] & {
        isActive: boolean;
        landlord: string;
        timestamp: bigint;
        isMatched: boolean;
      }
    ],
    "view"
  >;

  getMatchDetails: TypedContractMethod<
    [_matchId: BigNumberish],
    [
      [bigint, bigint, string, string, bigint, boolean, boolean, boolean] & {
        listingId: bigint;
        requestId: bigint;
        landlord: string;
        tenant: string;
        timestamp: bigint;
        isConfirmed: boolean;
        landlordConfirmed: boolean;
        tenantConfirmed: boolean;
      }
    ],
    "view"
  >;

  getPauserAtIndex: TypedContractMethod<
    [_index: BigNumberish],
    [string],
    "view"
  >;

  getPauserCount: TypedContractMethod<[], [bigint], "view">;

  getPlatformStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        totalListings: bigint;
        totalRequests: bigint;
        totalMatches: bigint;
        activeListings: bigint;
        activeRequests: bigint;
      }
    ],
    "view"
  >;

  getRequestDetails: TypedContractMethod<
    [_requestId: BigNumberish],
    [
      [boolean, string, bigint, boolean] & {
        isActive: boolean;
        tenant: string;
        timestamp: bigint;
        isMatched: boolean;
      }
    ],
    "view"
  >;

  getUserListings: TypedContractMethod<
    [_user: AddressLike],
    [bigint[]],
    "view"
  >;

  getUserRequests: TypedContractMethod<
    [_user: AddressLike],
    [bigint[]],
    "view"
  >;

  isContractPaused: TypedContractMethod<[], [boolean], "view">;

  isListingValid: TypedContractMethod<
    [_listingId: BigNumberish],
    [boolean],
    "view"
  >;

  isPaused: TypedContractMethod<[], [boolean], "view">;

  isPauser: TypedContractMethod<[_address: AddressLike], [boolean], "view">;

  isPauserAddress: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isPublicDecryptAllowed: TypedContractMethod<[], [boolean], "view">;

  isRequestValid: TypedContractMethod<
    [_requestId: BigNumberish],
    [boolean],
    "view"
  >;

  kmsGeneration: TypedContractMethod<[], [bigint], "view">;

  listingIdCounter: TypedContractMethod<[], [bigint], "view">;

  listings: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, boolean, string, bigint, boolean] & {
        encryptedPrice: string;
        encryptedBedrooms: string;
        encryptedPostalCode: string;
        encryptedPropertyType: string;
        isActive: boolean;
        landlord: string;
        timestamp: bigint;
        isMatched: boolean;
      }
    ],
    "view"
  >;

  matchCounter: TypedContractMethod<[], [bigint], "view">;

  matches: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, string, bigint, boolean, boolean, boolean] & {
        listingId: bigint;
        requestId: bigint;
        landlord: string;
        tenant: string;
        timestamp: bigint;
        isConfirmed: boolean;
        landlordConfirmed: boolean;
        tenantConfirmed: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  pauserAddresses: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  removePauser: TypedContractMethod<
    [_pauser: AddressLike],
    [void],
    "nonpayable"
  >;

  requestDecryption: TypedContractMethod<
    [_encryptedValue: BytesLike],
    [bigint],
    "nonpayable"
  >;

  requestIdCounter: TypedContractMethod<[], [bigint], "view">;

  requests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, boolean, string, bigint, boolean] & {
        encryptedMaxBudget: string;
        encryptedMinBedrooms: string;
        encryptedPreferredPostalCode: string;
        encryptedPreferredPropertyType: string;
        isActive: boolean;
        tenant: string;
        timestamp: bigint;
        isMatched: boolean;
      }
    ],
    "view"
  >;

  submitDecryptionResponse: TypedContractMethod<
    [
      _requestId: BigNumberish,
      _encryptedShare: BytesLike,
      _signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateKmsGeneration: TypedContractMethod<
    [_newGeneration: BigNumberish],
    [void],
    "nonpayable"
  >;

  userListings: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  userRequests: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addPauser"
  ): TypedContractMethod<[_pauser: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confirmMatch"
  ): TypedContractMethod<[_matchId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createListing"
  ): TypedContractMethod<
    [
      _price: BigNumberish,
      _bedrooms: BigNumberish,
      _postalCode: BigNumberish,
      _propertyType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createMatch"
  ): TypedContractMethod<
    [_listingId: BigNumberish, _requestId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createRequest"
  ): TypedContractMethod<
    [
      _maxBudget: BigNumberish,
      _minBedrooms: BigNumberish,
      _preferredPostalCode: BigNumberish,
      _preferredPropertyType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deactivateListing"
  ): TypedContractMethod<[_listingId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deactivateRequest"
  ): TypedContractMethod<[_requestId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "decryptionRequestCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "decryptionRequests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, boolean, bigint] & {
        requestId: bigint;
        requester: string;
        encryptedValue: string;
        timestamp: bigint;
        fulfilled: boolean;
        kmsGeneration: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "emergencyPause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getActiveListingsCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getActiveRequestsCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getListingDetails"
  ): TypedContractMethod<
    [_listingId: BigNumberish],
    [
      [boolean, string, bigint, boolean] & {
        isActive: boolean;
        landlord: string;
        timestamp: bigint;
        isMatched: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMatchDetails"
  ): TypedContractMethod<
    [_matchId: BigNumberish],
    [
      [bigint, bigint, string, string, bigint, boolean, boolean, boolean] & {
        listingId: bigint;
        requestId: bigint;
        landlord: string;
        tenant: string;
        timestamp: bigint;
        isConfirmed: boolean;
        landlordConfirmed: boolean;
        tenantConfirmed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPauserAtIndex"
  ): TypedContractMethod<[_index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getPauserCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPlatformStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        totalListings: bigint;
        totalRequests: bigint;
        totalMatches: bigint;
        activeListings: bigint;
        activeRequests: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRequestDetails"
  ): TypedContractMethod<
    [_requestId: BigNumberish],
    [
      [boolean, string, bigint, boolean] & {
        isActive: boolean;
        tenant: string;
        timestamp: bigint;
        isMatched: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserListings"
  ): TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getUserRequests"
  ): TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "isContractPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isListingValid"
  ): TypedContractMethod<[_listingId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPauser"
  ): TypedContractMethod<[_address: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPauserAddress"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPublicDecryptAllowed"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRequestValid"
  ): TypedContractMethod<[_requestId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "kmsGeneration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "listingIdCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "listings"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, boolean, string, bigint, boolean] & {
        encryptedPrice: string;
        encryptedBedrooms: string;
        encryptedPostalCode: string;
        encryptedPropertyType: string;
        isActive: boolean;
        landlord: string;
        timestamp: bigint;
        isMatched: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "matchCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "matches"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, string, bigint, boolean, boolean, boolean] & {
        listingId: bigint;
        requestId: bigint;
        landlord: string;
        tenant: string;
        timestamp: bigint;
        isConfirmed: boolean;
        landlordConfirmed: boolean;
        tenantConfirmed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "pauserAddresses"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "removePauser"
  ): TypedContractMethod<[_pauser: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestDecryption"
  ): TypedContractMethod<[_encryptedValue: BytesLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "requestIdCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "requests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, boolean, string, bigint, boolean] & {
        encryptedMaxBudget: string;
        encryptedMinBedrooms: string;
        encryptedPreferredPostalCode: string;
        encryptedPreferredPropertyType: string;
        isActive: boolean;
        tenant: string;
        timestamp: bigint;
        isMatched: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitDecryptionResponse"
  ): TypedContractMethod<
    [
      _requestId: BigNumberish,
      _encryptedShare: BytesLike,
      _signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateKmsGeneration"
  ): TypedContractMethod<[_newGeneration: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userListings"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "userRequests"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "ContractPaused"
  ): TypedContractEvent<
    ContractPausedEvent.InputTuple,
    ContractPausedEvent.OutputTuple,
    ContractPausedEvent.OutputObject
  >;
  getEvent(
    key: "ContractUnpaused"
  ): TypedContractEvent<
    ContractUnpausedEvent.InputTuple,
    ContractUnpausedEvent.OutputTuple,
    ContractUnpausedEvent.OutputObject
  >;
  getEvent(
    key: "DecryptionRequested"
  ): TypedContractEvent<
    DecryptionRequestedEvent.InputTuple,
    DecryptionRequestedEvent.OutputTuple,
    DecryptionRequestedEvent.OutputObject
  >;
  getEvent(
    key: "DecryptionResponse"
  ): TypedContractEvent<
    DecryptionResponseEvent.InputTuple,
    DecryptionResponseEvent.OutputTuple,
    DecryptionResponseEvent.OutputObject
  >;
  getEvent(
    key: "KmsGenerationUpdated"
  ): TypedContractEvent<
    KmsGenerationUpdatedEvent.InputTuple,
    KmsGenerationUpdatedEvent.OutputTuple,
    KmsGenerationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ListingCreated"
  ): TypedContractEvent<
    ListingCreatedEvent.InputTuple,
    ListingCreatedEvent.OutputTuple,
    ListingCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ListingDeactivated"
  ): TypedContractEvent<
    ListingDeactivatedEvent.InputTuple,
    ListingDeactivatedEvent.OutputTuple,
    ListingDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "MatchConfirmed"
  ): TypedContractEvent<
    MatchConfirmedEvent.InputTuple,
    MatchConfirmedEvent.OutputTuple,
    MatchConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "MatchCreated"
  ): TypedContractEvent<
    MatchCreatedEvent.InputTuple,
    MatchCreatedEvent.OutputTuple,
    MatchCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PauserAdded"
  ): TypedContractEvent<
    PauserAddedEvent.InputTuple,
    PauserAddedEvent.OutputTuple,
    PauserAddedEvent.OutputObject
  >;
  getEvent(
    key: "PauserRemoved"
  ): TypedContractEvent<
    PauserRemovedEvent.InputTuple,
    PauserRemovedEvent.OutputTuple,
    PauserRemovedEvent.OutputObject
  >;
  getEvent(
    key: "RequestCreated"
  ): TypedContractEvent<
    RequestCreatedEvent.InputTuple,
    RequestCreatedEvent.OutputTuple,
    RequestCreatedEvent.OutputObject
  >;
  getEvent(
    key: "RequestDeactivated"
  ): TypedContractEvent<
    RequestDeactivatedEvent.InputTuple,
    RequestDeactivatedEvent.OutputTuple,
    RequestDeactivatedEvent.OutputObject
  >;

  filters: {
    "ContractPaused(address,uint256)": TypedContractEvent<
      ContractPausedEvent.InputTuple,
      ContractPausedEvent.OutputTuple,
      ContractPausedEvent.OutputObject
    >;
    ContractPaused: TypedContractEvent<
      ContractPausedEvent.InputTuple,
      ContractPausedEvent.OutputTuple,
      ContractPausedEvent.OutputObject
    >;

    "ContractUnpaused(address,uint256)": TypedContractEvent<
      ContractUnpausedEvent.InputTuple,
      ContractUnpausedEvent.OutputTuple,
      ContractUnpausedEvent.OutputObject
    >;
    ContractUnpaused: TypedContractEvent<
      ContractUnpausedEvent.InputTuple,
      ContractUnpausedEvent.OutputTuple,
      ContractUnpausedEvent.OutputObject
    >;

    "DecryptionRequested(uint256,address,uint256,bytes32,uint256)": TypedContractEvent<
      DecryptionRequestedEvent.InputTuple,
      DecryptionRequestedEvent.OutputTuple,
      DecryptionRequestedEvent.OutputObject
    >;
    DecryptionRequested: TypedContractEvent<
      DecryptionRequestedEvent.InputTuple,
      DecryptionRequestedEvent.OutputTuple,
      DecryptionRequestedEvent.OutputObject
    >;

    "DecryptionResponse(uint256,address,bytes,bytes,uint256)": TypedContractEvent<
      DecryptionResponseEvent.InputTuple,
      DecryptionResponseEvent.OutputTuple,
      DecryptionResponseEvent.OutputObject
    >;
    DecryptionResponse: TypedContractEvent<
      DecryptionResponseEvent.InputTuple,
      DecryptionResponseEvent.OutputTuple,
      DecryptionResponseEvent.OutputObject
    >;

    "KmsGenerationUpdated(uint256,uint256)": TypedContractEvent<
      KmsGenerationUpdatedEvent.InputTuple,
      KmsGenerationUpdatedEvent.OutputTuple,
      KmsGenerationUpdatedEvent.OutputObject
    >;
    KmsGenerationUpdated: TypedContractEvent<
      KmsGenerationUpdatedEvent.InputTuple,
      KmsGenerationUpdatedEvent.OutputTuple,
      KmsGenerationUpdatedEvent.OutputObject
    >;

    "ListingCreated(uint256,address)": TypedContractEvent<
      ListingCreatedEvent.InputTuple,
      ListingCreatedEvent.OutputTuple,
      ListingCreatedEvent.OutputObject
    >;
    ListingCreated: TypedContractEvent<
      ListingCreatedEvent.InputTuple,
      ListingCreatedEvent.OutputTuple,
      ListingCreatedEvent.OutputObject
    >;

    "ListingDeactivated(uint256)": TypedContractEvent<
      ListingDeactivatedEvent.InputTuple,
      ListingDeactivatedEvent.OutputTuple,
      ListingDeactivatedEvent.OutputObject
    >;
    ListingDeactivated: TypedContractEvent<
      ListingDeactivatedEvent.InputTuple,
      ListingDeactivatedEvent.OutputTuple,
      ListingDeactivatedEvent.OutputObject
    >;

    "MatchConfirmed(uint256,address)": TypedContractEvent<
      MatchConfirmedEvent.InputTuple,
      MatchConfirmedEvent.OutputTuple,
      MatchConfirmedEvent.OutputObject
    >;
    MatchConfirmed: TypedContractEvent<
      MatchConfirmedEvent.InputTuple,
      MatchConfirmedEvent.OutputTuple,
      MatchConfirmedEvent.OutputObject
    >;

    "MatchCreated(uint256,uint256,uint256)": TypedContractEvent<
      MatchCreatedEvent.InputTuple,
      MatchCreatedEvent.OutputTuple,
      MatchCreatedEvent.OutputObject
    >;
    MatchCreated: TypedContractEvent<
      MatchCreatedEvent.InputTuple,
      MatchCreatedEvent.OutputTuple,
      MatchCreatedEvent.OutputObject
    >;

    "PauserAdded(address,uint256)": TypedContractEvent<
      PauserAddedEvent.InputTuple,
      PauserAddedEvent.OutputTuple,
      PauserAddedEvent.OutputObject
    >;
    PauserAdded: TypedContractEvent<
      PauserAddedEvent.InputTuple,
      PauserAddedEvent.OutputTuple,
      PauserAddedEvent.OutputObject
    >;

    "PauserRemoved(address,uint256)": TypedContractEvent<
      PauserRemovedEvent.InputTuple,
      PauserRemovedEvent.OutputTuple,
      PauserRemovedEvent.OutputObject
    >;
    PauserRemoved: TypedContractEvent<
      PauserRemovedEvent.InputTuple,
      PauserRemovedEvent.OutputTuple,
      PauserRemovedEvent.OutputObject
    >;

    "RequestCreated(uint256,address)": TypedContractEvent<
      RequestCreatedEvent.InputTuple,
      RequestCreatedEvent.OutputTuple,
      RequestCreatedEvent.OutputObject
    >;
    RequestCreated: TypedContractEvent<
      RequestCreatedEvent.InputTuple,
      RequestCreatedEvent.OutputTuple,
      RequestCreatedEvent.OutputObject
    >;

    "RequestDeactivated(uint256)": TypedContractEvent<
      RequestDeactivatedEvent.InputTuple,
      RequestDeactivatedEvent.OutputTuple,
      RequestDeactivatedEvent.OutputObject
    >;
    RequestDeactivated: TypedContractEvent<
      RequestDeactivatedEvent.InputTuple,
      RequestDeactivatedEvent.OutputTuple,
      RequestDeactivatedEvent.OutputObject
    >;
  };
}
